const suits=['♠','♥','♦','♣'], vals=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const MODES={easy:{name:'Easy',title:'🟢 Лёгкий',desc:'по 1 карте, бесконечная колода, подсказки и авто'},normal:{name:'Normal',title:'🟡 Средний',desc:'по 3 карты, 3 прохода колоды'},hard:{name:'Hard',title:'🔴 Сложный',desc:'по 3 карты, 1 проход, без подсказок'},pro:{name:'Pro',title:'💀 Pro',desc:'по 3 карты, 1 проход, штраф за отмену'},vegas:{name:'Vegas',title:'💰 Vegas',desc:'по 3 карты, 1 проход, счёт начинается с -52'}};
const CFG={easy:{draw:1,passes:999,hint:true,auto:true,undoPenalty:0,startScore:0},normal:{draw:3,passes:3,hint:true,auto:true,undoPenalty:0,startScore:0},hard:{draw:3,passes:1,hint:false,auto:false,undoPenalty:0,startScore:0},pro:{draw:3,passes:1,hint:false,auto:false,undoPenalty:5,startScore:0},vegas:{draw:3,passes:1,hint:false,auto:false,undoPenalty:0,startScore:-52}};
const el=id=>document.getElementById(id); const red=s=>s==='♥'||s==='♦'; const rank=v=>vals.indexOf(v)+1;
let state,history=[],selected=null,timerId=null,startTs=0,lastTap={id:null,t:0},drag=null,suppressClickUntil=0,currentMode=localStorage.kosynka_v3_mode||'normal';
function key(){return 'kosynka_v3_'+currentMode} function statKey(){return 'kosynka_v3_stats'}
function toast(t){const x=el('toast');x.textContent=t;x.classList.add('show');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove('show'),1300)}
function stats(){return JSON.parse(localStorage[statKey()]||'{}')} function saveStats(s){localStorage[statKey()]=JSON.stringify(s)}
function updateStatsUI(){let s=stats()[currentMode]||{wins:0,streak:0,best:null};el('wins').textContent=s.wins||0;el('streak').textContent=s.streak||0;el('best').textContent=s.best?fmt(s.best):'—'}
function newDeck(){let d=[];for(const s of suits)for(const v of vals)d.push({id:s+v+suits.indexOf(s)+rank(v)+Math.random().toString(36).slice(2,5),suit:s,value:v,face:false});for(let i=d.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function deal(){let d=newDeck(),c=CFG[currentMode]; state={mode:currentMode,stock:[],waste:[],found:[[],[],[],[]],tab:[[],[],[],[],[],[],[]],moves:0,score:c.startScore,elapsed:0,passesLeft:c.passes,won:false}; history=[]; for(let col=0;col<7;col++)for(let r=0;r<=col;r++){let card=d.pop();card.face=r===col;state.tab[col].push(card)} state.stock=d; save(); tick(); render(); toast('Новая игра: '+MODES[currentMode].name)}
function load(){try{state=JSON.parse(localStorage[key()]||'null')}catch(e){state=null} if(!state)deal(); else {tick();render()}}
function clone(){return JSON.stringify(state)} function push(){history.push(clone());if(history.length>120)history.shift()} function save(){localStorage[key()]=JSON.stringify(state);localStorage.kosynka_v3_mode=currentMode}
function tick(){clearInterval(timerId);startTs=Date.now()-(state?.elapsed||0)*1000;timerId=setInterval(()=>{if(state&&!state.won){state.elapsed=Math.floor((Date.now()-startTs)/1000);el('timer').textContent=fmt(state.elapsed);save()}},1000)}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function render(){el('modeBadge').textContent=MODES[currentMode].name;el('moves').textContent=state.moves;el('score').textContent=state.score;el('timer').textContent=fmt(state.elapsed||0);updateStatsUI();el('hint').disabled=!CFG[currentMode].hint;el('auto').disabled=!CFG[currentMode].auto;
 const st=el('stock');st.innerHTML=state.stock.length?'<div class="card back" style="left:50%;top:0"></div>':`<span class="empty">${state.passesLeft>1?'↻':''}</span>`;st.onclick=draw;
 const w=el('waste');w.innerHTML='';state.waste.slice(-3).forEach((c,i,a)=>w.appendChild(cardEl(c,{type:'waste',index:state.waste.length-a.length+i},0)));
 const f=el('foundations');f.innerHTML='';for(let i=0;i<4;i++){let div=document.createElement('div');div.className='foundation';div.dataset.type='found';div.dataset.index=i;div.textContent=state.found[i].length?'':'A';let top=state.found[i].at(-1); if(top)div.appendChild(cardEl(top,{type:'found',pile:i,index:state.found[i].length-1},0));f.appendChild(div)}
 const t=el('tableau');t.innerHTML='';for(let i=0;i<7;i++){let p=document.createElement('div');p.className='pile';p.dataset.type='tab';p.dataset.index=i;state.tab[i].forEach((c,j)=>p.appendChild(cardEl(c,{type:'tab',pile:i,index:j},j*22)));t.appendChild(p)} attachZones();}
function cardEl(c,loc,top){let d=document.createElement('div');d.className='card '+(red(c.suit)?'red ':'')+(c.face?'':'back');d.dataset.id=c.id;d.dataset.loc=JSON.stringify(loc);d.style.top=top+'px'; if(c.face){d.innerHTML=`<div class="topv">${c.value}<br>${c.suit}</div><div class="mid">${c.suit}</div><div class="bot">${c.value}<br>${c.suit}</div>`;d.addEventListener('pointerdown',onPointer);d.addEventListener('click',onCardClick);d.addEventListener('dblclick',onCardDoubleClick)}return d}
function draw(){push(); const c=CFG[currentMode]; if(state.stock.length){for(let i=0;i<c.draw&&state.stock.length;i++){let card=state.stock.pop();card.face=true;state.waste.push(card)}state.moves++}else if(state.waste.length&&state.passesLeft>1){state.passesLeft--;state.stock=state.waste.reverse().map(x=>({...x,face:false}));state.waste=[];state.moves++}else toast('Колода закончилась'); save();render()}
function getCards(loc){if(!loc)return[];if(loc.type==='waste')return state.waste.length?[state.waste.at(-1)]:[];if(loc.type==='found')return state.found[loc.pile].length?[state.found[loc.pile].at(-1)]:[];if(loc.type==='tab')return state.tab[loc.pile].slice(loc.index);return[]}
function removeCards(loc){if(loc.type==='waste')return [state.waste.pop()];if(loc.type==='found')return [state.found[loc.pile].pop()];if(loc.type==='tab')return state.tab[loc.pile].splice(loc.index);return[]}
function canFound(card,pile){const f=state.found[pile];return f.length?f.at(-1).suit===card.suit&&rank(card.value)===rank(f.at(-1).value)+1:card.value==='A'}
function canTab(cards,pile){const c=cards[0],p=state.tab[pile];if(!c)return false;if(!p.length)return c.value==='K';const top=p.at(-1);return top.face&&red(top.suit)!==red(c.suit)&&rank(c.value)===rank(top.value)-1}
function move(loc,to,silent=false){let cards=getCards(loc);if(!cards.length)return false;let ok=false;if(to.type==='found'&&cards.length===1)ok=canFound(cards[0],to.pile);if(to.type==='tab')ok=canTab(cards,to.pile);if(!ok)return false;push();cards=removeCards(loc);if(to.type==='found'){state.found[to.pile].push(cards[0]);state.score+=currentMode==='vegas'?5:10}else{state.tab[to.pile].push(...cards);state.score+=loc.type==='waste'?5:0}if(loc.type==='tab'){let p=state.tab[loc.pile];if(p.length&&!p.at(-1).face){p.at(-1).face=true;state.score+=5}}state.moves++;selected=null;save();render();checkWin();return true}
function handleCardTap(loc){const c=getCards(loc)[0];let now=Date.now();if(lastTap.id===c?.id&&now-lastTap.t<520){lastTap={id:null,t:0};tryAutoPlace(loc,true);return}lastTap={id:c?.id,t:now};selectOrMove(loc)}
function onCardClick(e){e.stopPropagation();if(Date.now()<suppressClickUntil)return;const loc=JSON.parse(e.currentTarget.dataset.loc);handleCardTap(loc)}
function onCardDoubleClick(e){e.preventDefault();e.stopPropagation();const loc=JSON.parse(e.currentTarget.dataset.loc);lastTap={id:null,t:0};tryAutoPlace(loc,true)}
function tryAutoPlace(loc,msg=false){let cards=getCards(loc);if(!cards.length)return false;for(let i=0;i<4;i++)if(cards.length===1&&canFound(cards[0],i))return move(loc,{type:'found',pile:i});for(let i=0;i<7;i++)if(!(loc.type==='tab'&&loc.pile===i)&&canTab(cards,i))return move(loc,{type:'tab',pile:i});if(msg)toast('Нет доступного места');return false}
function selectOrMove(loc){if(selected){if(loc.type==='tab'&&move(selected,{type:'tab',pile:loc.pile}))return;if(loc.type==='found'&&move(selected,{type:'found',pile:loc.pile}))return;selected=null;render()}else{selected=loc;document.querySelectorAll('.card').forEach(x=>x.classList.remove('selected'));let card=document.querySelector(`[data-id="${getCards(loc)[0]?.id}"]`);if(card)card.classList.add('selected')}}
function attachZones(){document.querySelectorAll('.pile,.foundation').forEach(z=>z.onclick=e=>{if(e.target.classList.contains('card'))return;if(!selected)return;move(selected,{type:z.dataset.type==='found'?'found':'tab',pile:+z.dataset.index})})}
function onPointer(e){const loc=JSON.parse(e.currentTarget.dataset.loc),cards=getCards(loc);if(!cards.length)return;drag={loc,cards,startX:e.clientX,startY:e.clientY,ghosts:[]};for(const c of cards){let node=document.querySelector(`[data-id="${c.id}"]`);if(node){let r=node.getBoundingClientRect(),g=node.cloneNode(true);g.classList.add('dragging');g.style.left=r.left+'px';g.style.top=r.top+'px';g.style.position='fixed';g.style.transform='none';document.body.appendChild(g);drag.ghosts.push({g,x:r.left,y:r.top})}}window.addEventListener('pointermove',dragMove);window.addEventListener('pointerup',dragEnd,{once:true})}
function dragMove(e){if(!drag)return;let dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;drag.ghosts.forEach(o=>{o.g.style.left=o.x+dx+'px';o.g.style.top=o.y+dy+'px'})}
function dragEnd(e){if(!drag)return;let dx=e.clientX-drag.startX,dy=e.clientY-drag.startY,moved=Math.hypot(dx,dy)>10;let loc=drag.loc,target=document.elementFromPoint(e.clientX,e.clientY),z=target?.closest?.('.pile,.foundation'),ok=false;if(moved&&z)ok=move(loc,{type:z.dataset.type==='found'?'found':'tab',pile:+z.dataset.index});drag.ghosts.forEach(o=>o.g.remove());drag=null;window.removeEventListener('pointermove',dragMove);if(!moved){suppressClickUntil=Date.now()+350;handleCardTap(loc);return}if(!ok)render()}
function allLocs(){let a=[];if(state.waste.length)a.push({type:'waste',index:state.waste.length-1});for(let i=0;i<7;i++){let first=state.tab[i].findIndex(c=>c.face);if(first>=0)for(let j=first;j<state.tab[i].length;j++)a.push({type:'tab',pile:i,index:j})}return a}
function hint(){for(const loc of allLocs()){let cards=getCards(loc);for(let i=0;i<4;i++)if(cards.length===1&&canFound(cards[0],i)){toast('Можно в дом: '+cards[0].value+cards[0].suit);return}for(let i=0;i<7;i++)if(!(loc.type==='tab'&&loc.pile===i)&&canTab(cards,i)){toast('Можно переложить: '+cards[0].value+cards[0].suit);return}}toast('Ходов не найдено')}
function auto(){let n=0,changed=true;while(changed&&n<100){changed=false;for(const loc of allLocs()){let cards=getCards(loc);if(cards.length===1){for(let i=0;i<4;i++)if(canFound(cards[0],i)){move(loc,{type:'found',pile:i});changed=true;n++;break}}if(changed)break}}toast(n?'Автоходов: '+n:'Автоходов нет')}
function checkWin(){if(state.won)return;if(state.found.every(f=>f.length===13)){state.won=true;let all=stats(),s=all[currentMode]||{wins:0,streak:0,best:null};s.wins++;s.streak++;if(!s.best||state.elapsed<s.best)s.best=state.elapsed;all[currentMode]=s;saveStats(all);save();render();toast('Победа! 🎉')}}
function showMenu(){el('modal').classList.add('show')} function closeMenu(){el('modal').classList.remove('show')}
function buildModes(){let m=el('modes');m.innerHTML='';Object.keys(MODES).forEach(k=>{let b=document.createElement('button');b.className='mode';b.innerHTML=`<b>${MODES[k].title}</b><span>${MODES[k].desc}</span>`;b.onclick=()=>{currentMode=k;closeMenu();deal()};m.appendChild(b)})}
el('menuBtn').onclick=showMenu;el('newGame').onclick=()=>deal();el('undo').onclick=()=>{if(history.length){state=JSON.parse(history.pop());if(CFG[currentMode].undoPenalty)state.score-=CFG[currentMode].undoPenalty;save();render()}else toast('Отменять нечего')};el('hint').onclick=()=>CFG[currentMode].hint?hint():toast('В этом режиме подсказки выключены');el('auto').onclick=()=>CFG[currentMode].auto?auto():toast('В этом режиме автоход выключен');el('continueBtn').onclick=()=>{closeMenu();load()};
buildModes(); if(localStorage[key()])load(); else deal(); if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=3.1').catch(()=>{});
